name: build
on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  id-token: write
  packages: write

env:
  IMAGE: ghcr.io/irr123/python-docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          VERSION=$GITHUB_REF_NAME make build
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push $IMAGE:$GITHUB_REF_NAME
